version: '3.7'
services:
  web:
    build: .
    ports:
    - "$PORT:80"
    environment:
    - PORT=80
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"e