name: Development CI/CD

on:
  push:
    branches: [ "main" ]

env:
  PORT: 8000
                                            
permissions:
  contents: read

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build, tag image
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg PORT="$PORT" -t "$IMAGE_TAG" .
        echo "::set-output name=image::$IMAGE_TAG"
